In [1]:
from fonctions.gestion_bdd import lire_bdd_perso, cancel
import pandas as pd

2023-03-22 20:25:53.469
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\Kevin\AppData\Roaming\Python\Python310\site-packages\ipykernel_launcher.py [ARGUMENTS]

In [2]:
cancel()

In [3]:
# df = lire_bdd_perso('''SELECT sw_monsters.*, sw_user.joueur from sw_monsters
#                     INNER JOIN sw_user ON sw_user.id = sw_monsters.id
#                     WHERE sw_user.id = 67
#                     ''', index_col='id').transpose().reset_index()

df = lire_bdd_perso('''SELECT sw_monsters.*, sw_user.joueur, sw_guilde.guilde from sw_monsters
                    INNER JOIN sw_user ON sw_user.id = sw_monsters.id
                    INNER JOIN sw_guilde ON sw_guilde.guilde_id = sw_user.guilde_id
                    ''', index_col='id').transpose().reset_index()

# df = lire_bdd_perso('''SELECT sw_monsters.*, sw_user.joueur from sw_monsters
#                     INNER JOIN sw_user ON sw_user.id = sw_monsters.id
#                     ''', index_col='id').transpose().reset_index()

In [4]:
df

        id id_monstre quantité storage  joueur        guilde
0      346      10102        1   False   Flow~     [Endless]
1      346      10131        2   False   Flow~     [Endless]
2      346      10132        1   False   Flow~     [Endless]
3      346      10214        1   False   Flow~     [Endless]
4      346      10313        1   False   Flow~     [Endless]
...    ...        ...      ...     ...     ...           ...
64446  323      12803        2    True  Kotarø  Annihilation
64447  323      12901        3    True  Kotarø  Annihilation
64448  323      12902        6    True  Kotarø  Annihilation
64449  323      12903        3    True  Kotarø  Annihilation
64450  323      13101        8    True  Kotarø  Annihilation

[64451 rows x 6 columns]

In [5]:
df2 = lire_bdd_perso('''SELECT * from sw_guilde''', index_col='guilde_id').transpose()

In [6]:
# df2.loc[df2['guilde'] == '[Endless]'].index.values[0]

In [7]:
swarfarm = pd.read_excel('swarfarm.xlsx')
swarfarm.drop('id', axis=1, inplace=True) # inutile ici

In [8]:
df_mob = pd.merge(df, swarfarm, left_on='id_monstre', right_on='com2us_id')

# df_mob = df_mob[df_mob['storage'] == False]

df_mob

,id,id_monstre,quantité,storage,joueur,guilde,url,com2us_id,family_id,name,...,skills,image_filename,natural_stars,awaken_level,id_leader,url_leader,attribute_leader,amount_leader,area_leader,element_leader
0,346,10102,1,False,Flow~,[Endless],https://swarfarm.com/api/v2/monsters/183/,10102,10100,Fairy Fire,...,"[61, 62, 63]",unit_icon_0000_1_0.png,3,0,Aucun,Aucun,Aucun,Aucun,Aucun,Aucun
1,346,10102,72,True,Flow~,[Endless],https://swarfarm.com/api/v2/monsters/183/,10102,10100,Fairy Fire,...,"[61, 62, 63]",unit_icon_0000_1_0.png,3,0,Aucun,Aucun,Aucun,Aucun,Aucun,Aucun
2,321,10102,25,True,Vεldrα,[Endless],https://swarfarm.com/api/v2/monsters/183/,10102,10100,Fairy Fire,...,"[61, 62, 63]",unit_icon_0000_1_0.png,3,0,Aucun,Aucun,Aucun,Aucun,Aucun,Aucun
3,27,10102,2,False,Resuroc_,Aucune,https://swarfarm.com/api/v2/monsters/183/,10102,10100,Fairy Fire,...,"[61, 62, 63]",unit_icon_0000_1_0.png,3,0,Aucun,Aucun,Aucun,Aucun,Aucun,Aucun
4,27,10102,23,True,Resuroc_,Aucune,https://swarfarm.com/api/v2/monsters/183/,10102,10100,Fairy Fire,...,"[61, 62, 63]",unit_icon_0000_1_0.png,3,0,Aucun,Aucun,Aucun,Aucun,Aucun,Aucun
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64446,67,14503,1,False,Tømløra,[Endless],https://swarfarm.com/api/v2/monsters/578/,14503,14500,Phoenix Wind,...,"[1173, 1180, 1181]",unit_icon_0009_2_0.png,5,0,138,https://swarfarm.com/api/v2/leader-skills/138/,Critical Rate,33,Dungeon,Aucun
64447,67,19714,1,False,Tømløra,[Endless],https://swarfarm.com/api/v2/monsters/848/,19714,19700,Pontos,...,"[1221, 1227, 1231]",unit_icon_0035_3_3.png,5,1,144,https://swarfarm.com/api/v2/leader-skills/144/,Attack Speed,24,General,Aucun
64448,67,24215,1,False,Tømløra,[Endless],https://swarfarm.com/api/v2/monsters/1651/,24215,24200,M. BISON,...,"[2751, 2756, 2761]",unit_icon_0061_1_5.png,5,1,154,https://swarfarm.com/api/v2/leader-skills/154/,Critical Rate,33,Arena,Aucun
64449,323,25104,1,False,Kotarø,Annihilation,https://swarfarm.com/api/v2/monsters/1810/,25104,25100,Onimusha Light,...,"[3088, 3093, 3098]",unit_icon_0073_0_4.png,4,0,Aucun,Aucun,Aucun,Aucun,Aucun,Aucun
64450,323,25104,1,True,Kotarø,Annihilation,https://swarfarm.com/api/v2/monsters/1810/,25104,25100,Onimusha Light,...,"[3088, 3093, 3098]",unit_icon_0073_0_4.png,4,0,Aucun,Aucun,Aucun,Aucun,Aucun,Aucun

In [9]:
df_mob_short = df_mob[['joueur', 'name', 'quantité', 'storage']]
df_mob_short

         joueur            name quantité storage
0         Flow~      Fairy Fire        1   False
1         Flow~      Fairy Fire       72    True
2        Vεldrα      Fairy Fire       25    True
3      Resuroc_      Fairy Fire        2   False
4      Resuroc_      Fairy Fire       23    True
...         ...             ...      ...     ...
64446   Tømløra    Phoenix Wind        1   False
64447   Tømløra          Pontos        1   False
64448   Tømløra        M. BISON        1   False
64449    Kotarø  Onimusha Light        1   False
64450    Kotarø  Onimusha Light        1    True

[64451 rows x 4 columns]

In [10]:
df_mob_complet = df_mob.groupby(['joueur', 'name']).agg({'quantité' :'sum'})
# on va supprimer le multiindex
df_mob_complet

                       quantité
joueur      name
*VNG*Justin Abellio           1
            Abigail           1
            Acasis            1
            Adriana           1
            Aegir             1
...                         ...
백소현         Yeti Light        2
            Yeti Water        4
            Yeti Wind         3
            Zaiross           1
            Zinc              2

[58693 rows x 1 columns]

In [11]:
# En terme de présentation celle-ci est mieux
selected_players = df_mob_complet.loc[([joueur for joueur in df_mob_complet.index.levels[0]], ['Lulu and Friends', 'Riley']), ['quantité']] 
selected_players

                              quantité
joueur       name
*VNG*Justin  Lulu and Friends        1
             Riley                   1
1ИV1ИC1BLE™  Lulu and Friends        6
             Riley                   3
AakaPsYkErS™ Lulu and Friends        6
...                                ...
彡Rno彡        Riley                   2
红蓝红蓝         Lulu and Friends        4
             Riley                   1
백소현          Lulu and Friends        1
             Riley                   1

[174 rows x 1 columns]

In [12]:
test = df_mob_complet.reset_index()

In [13]:
# En terme de lisibilité du code, celle-ci est mieux
# selected_players = test.loc[(test['name'].isin(['Lulu and Friends', 'Riley'])) & (test['quantité'] >= 1), ['joueur', 'name', 'quantité']]
selected_players = test.loc[(test['name'].isin(['Molly', 'Mermaid Light'])) & (test['quantité'] >= 1), ['joueur', 'name', 'quantité']]
selected_players

             joueur           name quantité
479     *VNG*Justin          Molly        1
1916   AakaPsYkErS™          Molly        3
2609         Aleski          Molly        1
4855       BIueEyes          Molly        1
5647         Baloo~          Molly        2
6404    CB|Eg'How2~          Molly        4
7099      Daijantai          Molly        1
7810       DarkZOUM          Molly        1
8552           Dev~          Molly        1
9948      EricLeBro          Molly        4
10714    Existence~          Molly        5
13360     Faucrire~          Molly        1
14047        FirelY          Molly        2
14586         Flodb          Molly        1
15196         Flow~          Molly        1
16463       FuBisha          Molly        1
17034         Glαɯı          Molly        2
17657    K.Tastroff          Molly        1
19022         Keu20          Molly        1
20561     Kobra~Kai          Molly        2
21363     Korn_Flex          Molly        2
22904        Kotarø  Mermaid Light        1
22927        Kotarø          Molly        5
23704        Kykii~          Molly        1
24319      LeArdØp~          Molly        2
24855  Leviosaaaaaa          Molly        1
25479      Levzelot          Molly        2
26732      MadCatz®          Molly        1
27243       Manol09          Molly        1
27745       Mik_Aya          Molly        1
28467      Mikuyato          Molly        1
31674     PowerDuot          Molly        3
32307      PsYkErS™          Molly        1
33549         Rach~          Molly        1
34315      Resuroc_          Molly        1
35084       Reyd1tv          Molly        1
36612        Sayric          Molly        1
39920       Spawari          Molly        2
40675   Specialized          Molly        1
41417       Tagfoot          Molly        1
42090   TaupeModele          Molly        1
42823    TinkerbeII          Molly        1
43563    TêteDeNeuf          Molly        1
44312       Tømløra          Molly        1
45103         Valhh          Molly        1
47251       YoSpach          Molly        1
47850      _Kaaaaaa  Mermaid Light        1
47869      _Kaaaaaa          Molly        2
48571       aakasia          Molly        1
51744       ~Tzzat~          Molly        2
54318        Иeøxys          Molly        1
56399           チアラ          Molly        1
57832          红蓝红蓝          Molly        1
58471           백소현          Molly        2

In [14]:
# Fonctionne avec les deux selected_players
selected_players.pivot_table(values='quantité', index='joueur', columns='name', aggfunc='sum', fill_value=0, margins=True, margins_name='Total')

name          Mermaid Light  Molly  Total
joueur
*VNG*Justin               0      1      1
AakaPsYkErS™              0      3      3
Aleski                    0      1      1
BIueEyes                  0      1      1
Baloo~                    0      2      2
CB|Eg'How2~               0      4      4
Daijantai                 0      1      1
DarkZOUM                  0      1      1
Dev~                      0      1      1
EricLeBro                 0      4      4
Existence~                0      5      5
Faucrire~                 0      1      1
FirelY                    0      2      2
Flodb                     0      1      1
Flow~                     0      1      1
FuBisha                   0      1      1
Glαɯı                     0      2      2
K.Tastroff                0      1      1
Keu20                     0      1      1
Kobra~Kai                 0      2      2
Korn_Flex                 0      2      2
Kotarø                    1      5      6
Kykii~                    0      1      1
LeArdØp~                  0      2      2
Leviosaaaaaa              0      1      1
Levzelot                  0      2      2
MadCatz®                  0      1      1
Manol09                   0      1      1
Mik_Aya                   0      1      1
Mikuyato                  0      1      1
PowerDuot                 0      3      3
PsYkErS™                  0      1      1
Rach~                     0      1      1
Resuroc_                  0      1      1
Reyd1tv                   0      1      1
Sayric                    0      1      1
Spawari                   0      2      2
Specialized               0      1      1
Tagfoot                   0      1      1
TaupeModele               0      1      1
TinkerbeII                0      1      1
TêteDeNeuf                0      1      1
Tømløra                   0      1      1
Valhh                     0      1      1
YoSpach                   0      1      1
_Kaaaaaa                  1      2      3
aakasia                   0      1      1
~Tzzat~                   0      2      2
Иeøxys                    0      1      1
チアラ                       0      1      1
红蓝红蓝                      0      1      1
백소현                       0      2      2
Total                     2     81     83